version: '3.9'

services:
  local-postgres-16:
    container_name: local-postgres-16
    image: postgres:16-alpine
    ports:
      - "5433:5432"
    environment:
      - POSTGRES_DB=formulaonebettingdb
      - POSTGRES_PASSWORD=password
      - POSTGRES_USER=postgres
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 512M